name: Generate Gifts action

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run the Node.js application
      run: npm start

    - name: Copy output file
      run: cp ./output/output.json .
    - name: Display files
      run: ls -li

    - name:  create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ github.run_number }}
          prerelease: false
          draft: false
          title: Gifts Output
          files: |
              output/*.json

