name: Generate Gifts action

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run the Node.js application
      run: npm start

    - name: Configure git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update data [skip ci]" || exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ github.run_number }}
        path: output/ # Replace 'output/' with the path to your folder containing files to upload
